---
- name: Deploy/build server
  hosts: deploy
  connection: local
  roles:
    - role: preconfig
      tags: preconfig
    - role: build
      tags: build
    - role: deploy
      tags: deploy
    # - swarm_init

- name: Manager
  hosts: managers
  connection: local
  roles:
    - role: preconfig
      tags: preconfig
    # - swarm_join

- name: Worker
  hosts: workers
  connection: local
  roles:
    - role: preconfig
      tags: preconfig
    # - swarm_join
