---
    - name: Установка докера
      block:
        - name: Добавляем universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
          # tags: universe

        - name: Установка дополнительных пакетов
          apt: 
            name:
             - ca-certificates 
             - curl 
             - gnupg 
             - lsb-release
             - python3-pip
            update-cache: yes
            cache_valid_time: 86400

        - name: Добавление ключа докер
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
            keyring: /usr/share/keyrings/docker-archive-keyring.gpg

        - name: Установка стабильного репозитория
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] 
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: yes
            filename: docker

        - name: Установка docker-ce
          apt: 
            name: docker-ce
            update-cache: yes

        - name: Проверка, что докер установлен и перезагружен
          service: 
            name: docker
            state: restarted
            enabled: yes
      become: true

    - name: Установка docker-compose
      block:
        - name: Получение последней версии docker-compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: Установка docker-compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: yes

    - name: Настройка дополнительных пакетов python
      block:
        - name: Установка pip пакетов
          pip:
            name: docker

    - name: Завершение установки
      block:
        - name: Добавление пользоателя в группу докер
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes

        #- name: Перезагрузка сервера
        #  reboot:
      become: yes